/** Belgaum / Belagavi school names for student school dropdown. */
export const BELGAUM_SCHOOL_NAMES = [
  "7TH DAY ADVENTURE SCHOOL",
  "ADARSH SCHOOL",
  "ADARSH VIDYA MANDIR",
  "BALIKA ADARSH VIDYALAY",
  "BHARATESH KAN MED SCHOOL",
  "BHARATESH SCHOOL",
  "BHARATI VIDYALAY SCHOOL",
  "CANTONMENT BOARD ENGLISH MEDIUM SCHOOL",
  "CANTONMENT BOARD SCHOOL",
  "D T DESAI PUBLIC SCHOOL",
  "DAIVADNYA ENG MED SCHOOL",
  "DIVINE PROVIDENCE SCHOOL",
  "DNYAN MANDIR ENG SCHOOL",
  "DNYAN PRABODHAN MANDIR",
  "DNYAN PRABHODINI MANDIR",
  "GAJANAN BHATKANDE HIGHSCHOOL",
  "GHPS NO 32",
  "GOMATESH ENGLISH MEDIUM SCHOOL",
  "GOMATESH HIGHSCHOOL KANNADA",
  "GOMTESH ENG MED PRIMARY SCHOOL",
  "GOMTESH HIGHSCHOOL KANNADA",
  "GOMTESH HIGHSCHOOL MARATHI",
  "GOMTESH SCHOOL ENGLISH",
  "GOMTESH SCHOOL KANNADA",
  "JAIN HERITAGE SCHOOL",
  "JAWAHAR NAVODAYA VIDYALAYA",
  "KAMDHENU ENGLISH MEDIUM HIGHSCHOOL",
  "KBS NO 3",
  "KBS NO 3 KHASBAG",
  "KENDRIYA VIDYALAYA",
  "KENDRIYA VIDYALAYA NO 2",
  "KENDRIY VIDYALAY NO 2",
  "KGPS NO 5",
  "KHGS NO 17",
  "KHPS NO 14",
  "KLE SOCIETY'S INTERNATIONAL SCHOOL",
  "KLS HIGH SCHOOL",
  "KLS PUBLIC SCHOOL",
  "KV NO 3",
  "LOVE DALE CENTRAL SCHOOL",
  "M R BHANDARI SCHOOL KANNADA",
  "M V HERAWADKAR HIGHSCHOOL",
  "MARATHA MANDAL JIJAMATA HIGHSCHOOL",
  "MARATHA MANDAL SCHOOL",
  "MUKTANGAN VIDYALAYA",
  "NEW GIRLS HIGHSCHOOL",
  "PANDIT NEHARU HIGHSCHOOL",
  "PHOENIX PUBLIC RESIDENTIAL SCHOOL",
  "PODAR INTERNATIONAL SCHOOL",
  "PRECIOUS BLOSSOM SCHOOL",
  "RASHTRIYA MILITARY SCHOOL",
  "SAINT XAVIOURS HIGHSCHOOL",
  "SANT MEERA HIGHSCHOOL",
  "SARASWATI GIRLS HIGHSCHOOL",
  "SHRI CHAITANYA TECHNO SCHOOL",
  "ST FRANCIS OF ASSISI SCHOOL",
  "ST PAUL'S HIGH SCHOOL",
  "SWADHYAY VIDYA MANDIR",
  "TATYASAHEB MUSALE SCHOOL",
  "THALAKWADI HIGHSCHOOL",
  "V M SHANBHAG MARATHI SCHOOL",
  "VANITA VIDYALAY",
] as const;

/** Select options; keeps a legacy/custom school value selectable when editing. */
export function schoolSelectOptions(current?: string): { value: string; label: string }[] {
  const names = new Set<string>(BELGAUM_SCHOOL_NAMES);
  const trimmed = current?.trim();
  if (trimmed) names.add(trimmed);

  return [
    { value: "", label: "Select school" },
    ...[...names]
      .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }))
      .map((name) => ({ value: name, label: name })),
  ];
}
